version: '3.8'

services:
  frontend:
    build:
      context: ./my_budget_angular_app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./my_budget_spring_app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_SERVER_URL=jdbc:mysql://mysql:3306/my_budget_db?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=CET&useSSL=false&allowPublicKeyRetrieval=true
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
    depends_on: 
      db: 
       condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USERNAME=root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "${MYSQL_ROOT_USERNAME}", "--password=${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 5

volumes:
  db-data:
 
